export const ERROR_CODES = [
  "LANHU_INVALID_ARGUMENT",
  "LANHU_AUTH_REQUIRED",
  "LANHU_AUTH_EXPIRED",
  "LANHU_AUTH_UNREADABLE",
  "LANHU_BROWSER_UNSUPPORTED",
  "LANHU_PERMISSION_DENIED",
  "LANHU_NETWORK_ERROR",
  "LANHU_API_ERROR",
  "LANHU_DESIGN_NOT_FOUND",
  "LANHU_DESIGN_AMBIGUOUS",
  "LANHU_INTERNAL_ERROR",
] as const;

export type LanhuErrorCode = (typeof ERROR_CODES)[number];

export const EXIT_CODE_BY_ERROR: Record<LanhuErrorCode, number> = {
  LANHU_INVALID_ARGUMENT: 2,
  LANHU_AUTH_REQUIRED: 3,
  LANHU_AUTH_EXPIRED: 3,
  LANHU_AUTH_UNREADABLE: 4,
  LANHU_BROWSER_UNSUPPORTED: 4,
  LANHU_PERMISSION_DENIED: 4,
  LANHU_NETWORK_ERROR: 5,
  LANHU_API_ERROR: 6,
  LANHU_DESIGN_NOT_FOUND: 7,
  LANHU_DESIGN_AMBIGUOUS: 7,
  LANHU_INTERNAL_ERROR: 1,
};
